name: Monitor 1-click Deployment

permissions: {}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - stage
          - prod
          - dev
      originalImageTag:
        description: 'The original image tag that has been deployed'
        required: true
        type: string
jobs:
  pull_retag_push:
    name: Pull, Retag, and Push Images
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: "read" # Needed for checkout
      id-token: "write" # Needed for GCP auth
      packages: "none" # Explicitly disable package permissions
    env:
      GAR_IMAGE_BASE: ${{ vars.GAR_REPO }}/${{ github.event.repository.name }}
      GAR_REGISTRY: us-docker.pkg.dev # Define GAR registry hostname
      DOCKERHUB_IMAGE: saansaan/blurts-server # Define Docker Hub image name
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false

    

    

      - name: Pull Docker Hub image
        run: docker pull ${{ env.DOCKERHUB_IMAGE }}:${{ inputs.originalImageTag }}

      - name: Retag Docker Hub image
        run: docker tag ${{ env.DOCKERHUB_IMAGE }}:${{ inputs.originalImageTag }} ${{ env.DOCKERHUB_IMAGE }}:${{ inputs.environment }}-${{ inputs.originalImageTag }}

      - name: Push Docker Hub image
        run: docker push ${{ env.DOCKERHUB_IMAGE }}:${{ inputs.environment }}-${{ inputs.originalImageTag }}

      - name: Pull GAR image
        run: docker pull ${{ env.GAR_IMAGE_BASE }}:${{ inputs.originalImageTag }}

      - name: Retag GAR image
        run: docker tag ${{ env.GAR_IMAGE_BASE }}:${{ inputs.originalImageTag }} ${{ env.GAR_IMAGE_BASE }}:${{ inputs.environment }}-${{ inputs.originalImageTag }}

      - name: Push GAR image
        run: docker push ${{ env.GAR_IMAGE_BASE }}:${{ inputs.environment }}-${{ inputs.originalImageTag }}
